name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  client-tests:
    name: Client Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - name: Install Client Dependencies
        run: npm install
      - name: Run Client Unit Tests
        run: npm test

  server-tests:
    name: Server Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Install Server Dependencies
        run: npm install
      - name: Run Server Unit Tests
        run: npm test
